name: barber
description: "Barber Club - Flutter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Networking
  dio: ^5.4.0
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Routing
  go_router: ^13.0.0
  
  # Deep Links
  app_links: ^6.3.1
  
  # URL Launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#000000"
  image: assets/images/barber_club_logo.png
  
  # This section is what fixes the white screen in your screenshot
  android_12:
    color: "#000000"
    image: assets/images/barber_club_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/barber_club_logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/barber_club_logo.png"


flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/barber_background.jpg
    - assets/images/barber_club_logo.png